service: server
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      DB_URL: mongodb+srv://varun:varun123@cluster0.6lqej.mongodb.net/krishVapes-Backend?retryWrites=true&w=majority
      PORT: 2014
      SECRET: "qwertyuiopl"
      KEY: KRISHVAPES1234
      ACCESS_TOKEN_TIME: "3d"
      REFRESH_TOKEN_TIME: "3d"
      CLOUD_NAME: "djgrqoefp"
      CLOUD_KEY: "274167243253962"
      CLOUD_SECRET: "3mkqkDDusI5Hf4flGNkJNz4PHYg"
